[package]
name = "matrix-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
clap = "4.3.17"
dotenv = "0.15.0"
reqwest = { version = "0.11.18", features = ["json", "native-tls"] }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
toml = "0.7.6"
