[package]
name = "matrix-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
clap = { version = "4.3.17", features = ["derive"] }
reqwest = { version = "0.11.18", features = ["json", "native-tls"] }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
thiserror = "1.0.43"
tokio = "1.29.1"
toml = "0.7.6"
