name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # Use nightly Rust to check the format
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          override: true
      - name: Check Format
        run: cargo fmt --all -- --check
      # Switch to stable Rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.67.0
          components: rustfmt, clippy
          override: true

      # Do tests
      - name: Check With Clippy
        run: cargo clippy --all-features
      - name: Run Tests
        run: RUST_TEST_THREADS=1 cargo test --all-features
